require("plugins.mason")
require("plugins.roslyn-nvim")
require("plugins.treesitter")
require("plugins.snacks")
require("plugins.colorscheme")
require("plugins.whichkey")
require("plugins.autopairs")
